# Configuration for areas to analyze for gaps in OLIMP questionnaire
# These sections will be analyzed to identify improvement opportunities
# Dynamically generated based on user priority selection

[gap_analysis]
target_sections = [
    "BUDGET",
    "PRODUCTS AND SERVICES",
    "ETHICS AND REGULATIONS"
]

# Generated at: 2025-06-18T08:39:25.930Z
# Selected areas count: 3
