[extract_answers]
extraction_prompt = """Analyze this Polish questionnaire PDF document and extract the structure in JSON format.

The document contains sections (OBSZAR), questions (PYTANIA), and answers (ODPOWIEDZI) with options A, B, C, D, E.
The selected answers are marked with "X" or "V" marks in the document. Look carefully at the visual layout:
- Each row represents a question
- Columns A, B, C, D, E contain the answer options
- The "X" or "V" mark appears in the column corresponding to the selected answer

CRITICAL: You must VERY CAREFULLY identify the exact column position of each "X" or "V" mark for every question. Take your time to:
1. Examine each row systematically from left to right
2. Identify which specific column (A, B, C, D, or E) contains the marking
3. Double-check the visual alignment between the mark and the column header
4. Be especially careful with marks that might appear between columns or slightly misaligned

IMPORTANT: The accuracy of answer extraction is crucial. Pay extremely close attention to which column contains the "X" or "V" mark for each question. This indicates the selected answer option.

Please extract:
1. Section names and their question counts
2. All questions within each section
3. All answer options (A, B, C, D, E) for each question
4. Which answer option is selected (marked with X or V) for each question - CAREFULLY examine the exact visual positioning and alignment of each mark with its corresponding column

Return the data in this JSON structure:
{{
  "questionnaire": "{questionnaire_type}",
  "questionnaire_title": "title of the questionnaire",
  "sections": [
    {{
      "section_name": "name of the section",
      "question_count": number_of_questions,
      "questions": [
        {{
          "question_text": "the question text",
          "answer_options": {{
            "A": "option A text",
            "B": "option B text", 
            "C": "option C text",
            "D": "option D text",
            "E": "option E text"
          }},
          "selected_answer": "A/B/C/D/E"
        }}
      ]
    }}
  ]
}}

Extract the data as JSON, making sure to correctly identify which column (A, B, C, D, or E) contains the "X" or "V" mark for each question.

FINAL CHECK: Before completing the extraction, systematically verify each selected_answer by re-examining the visual position of marks in the PDF to ensure 100% accuracy."""

[recommend]
recommendation_prompt = """You are an expert in digital transformation and AI implementation in organizations. 

NOTE: Use the latest, current information about AI technologies and best practices. 

Based on the gap analysis in OLIMP areas, prepare a detailed recommendation report for a company that wants to smoothly transition from its current state to level E (maximum) through transitional states.

The input data is a gap analysis in JSON format that contains:
- For each section (TECHNOLOGY AND INFRASTRUCTURE, PEOPLE AND COMPETENCIES, ORGANIZATION AND PROCESSES)
- For each question: current level (present) and steps to level E (steps)
- Each level contains a letter (A-E) and detailed description

REPORT STRUCTURE:
1. **Executive Summary**
   - Overall assessment of the organization's current state
   - Key areas requiring attention
   - Transformation priorities

2. **Analysis by Areas**
   - For each area present in the provided gaps data (analyze ONLY the areas included in the gaps JSON data, do not assume or add other areas):
     - Current state and main challenges
     - Recommended development paths
     - Concrete actions to take

3. **Implementation Plan**
   - Phase 1 (0-6 months): Pilot actions and foundations
   - Phase 2 (6-18 months): Development and scaling
   - Phase 3 (18-36 months): Optimization and excellence

4. **Resources and Budget**
   - Estimated budget for each phase
   - Required human resources
   - Technologies and tools to implement

5. **Success Indicators and Monitoring**
   - KPIs for each area
   - Ways to measure progress
   - Control points

6. **Potential Benefits and Gains**
   - Business benefits from AI implementation in each area of the new product development process
   - Estimated cost savings and efficiency improvements
   - Competitive advantage and new business opportunities
   - Long-term strategic benefits
   - Examples of specific improvements in the new product development process
   - Return on investment (ROI) and other measurable benefits

REQUIREMENTS:
- Report in English language
- Concrete, actionable recommendations
- Consideration of business specifics
- Realistic timelines
- Focus on smooth transition between levels
- CRITICAL: Analyze and provide recommendations ONLY for the areas present in the gaps data. Do not include recommendations for areas not listed in the gaps JSON.

Data for analysis:
{gaps_data}

ADDITIONAL CONTEXT:
Below are answers from one of the questionnaires (CLIMB_2), which may (but do not have to) be used as supplementary information for generating recommendations. This data can help in better understanding the organization's specifics and business context:

{supplementary_context}

Prepare a professional report in Markdown format."""

[evaluate]
evaluation_prompt = """
You are an expert in evaluating strategic business recommendations and digital transformation. Your task is to conduct a detailed evaluation of the recommendation report in terms of compliance with requirements and strategic quality.

## INPUT DATA
- **Original recommendation report**: {recommendations_report}
- **Source data (gap analysis)**: {original_gaps_data}
- **Supplementary context**: {original_supplementary_context}

## EVALUATION CRITERIA

### A. COMPLIANCE WITH STRUCTURAL REQUIREMENTS (40 points)

**1. Structural completeness (20 points)**
- Does the report contain all 6 required sections?
- Does each section have appropriate depth and detail?
- Rating: 0-20 points

**2. Jakość zawartości sekcji (20 punktów)**
- **Streszczenie wykonawcze**: Czy zawiera ogólną ocenę, kluczowe obszary, priorytety?
- **Analiza według obszarów**: Czy pokrywa wszystkie 3 obszary OLIMP z obecnym stanem, ścieżkami rozwoju i konkretnymi działaniami?
- **Plan implementacji**: Czy zawiera realistyczne 3 fazy z określonymi timelinami?
- **Zasoby i budżet**: Czy podaje szacunkowe koszty, zasoby ludzkie, technologie?
- **Wskaźniki sukcesu**: Czy definiuje KPI, sposoby mierzenia, punkty kontrolne?
- **Korzyści i zyski**: Czy szczegółowo opisuje korzyści biznesowe, ROI, przewagę konkurencyjną?
- Ocena: 0-20 punktów

### B. JAKOŚĆ STRATEGICZNA REKOMENDACJI (35 punktów)

**3. Konkretność i wykonalność (15 punktów)**
- Czy rekomendacje są konkretne i szczegółowe?
- Czy działania są wykonalne i realistyczne?
- Czy podano jasne kroki implementacji?
- Ocena: 0-15 punktów

**4. Logiczność i spójność (10 punktów)**
- Czy rekomendacje logicznie wynikają z analizy luk?
- Czy plan jest spójny wewnętrznie?
- Czy timeline jest realistyczny?
- Ocena: 0-10 punktów

**5. Dostosowanie do kontekstu (10 punktów)**
- Czy rekomendacje uwzględniają specyfikę organizacji?
- Czy wykorzystano dane z kontekstu uzupełniającego?
- Czy poziom dojrzałości jest właściwie oszacowany?
- Ocena: 0-10 punktów

### C. NAJLEPSZE PRAKTYKI STRATEGICZNE (25 punktów)

**6. Priorytetyzacja i sekwencjonowanie (10 punktów)**
- Czy działania są odpowiednio priorytetyzowane?
- Czy sekwencja implementacji ma sens biznesowy?
- Czy uwzględniono zależności między działaniami?
- Ocena: 0-10 punktów

**7. Zarządzanie ryzykiem i mitalizacja (8 punktów)**
- Czy zidentyfikowano potencjalne ryzyka?
- Czy zaproponowano działania mitygujące?
- Czy plan zawiera alternatywne scenariusze?
- Ocena: 0-8 punktów

**8. Mierzalność i monitoring (7 punktów)**
- Czy wskaźniki są SMART (konkretne, mierzalne, osiągalne, istotne, terminowe)?
- Czy zdefiniowano bazeline i cele?
- Czy system monitoringu jest praktyczny?
- Ocena: 0-7 punktów

## FORMAT ODPOWIEDZI

Przygotuj szczegółową ocenę w następującym formacie:

### PODSUMOWANIE OCENY
- **Łączny wynik**: [X/100 punktów]
- **Poziom jakości**: [Doskonały (90-100) / Bardzo dobry (80-89) / Dobry (70-79) / Wymagający poprawy (60-69) / Niewystarczający (<60)]

### SZCZEGÓŁOWA ANALIZA PUNKTOWA

#### A. Zgodność z wymaganiami strukturalnymi (X/40)
1. **Kompletność struktury (X/20)**
   - Analiza: [szczegółowy opis]
   - Braki: [jeśli występują]

2. **Jakość zawartości sekcji (X/20)**
   - Analiza każdej sekcji
   - Mocne strony i słabości

#### B. Jakość strategiczna rekomendacji (X/35)
3. **Konkretność i wykonalność (X/15)**
   - Ocena poziomu szczegółowości
   - Przykłady dobrych/słabych rekomendacji

4. **Logiczność i spójność (X/10)**
   - Analiza spójności wewnętrznej
   - Ocena timeline'ów

5. **Dostosowanie do kontekstu (X/10)**
   - Jak wykorzystano dane źródłowe
   - Stopień personalizacji

#### C. Najlepsze praktyki strategiczne (X/25)
6. **Priorytetyzacja i sekwencjonowanie (X/10)**
   - Ocena logiki priorytetów
   - Analiza sekwencji działań

7. **Zarządzanie ryzykiem (X/8)**
   - Identyfikacja braków w zarządzaniu ryzykiem
   - Sugestie uzupełnień

8. **Mierzalność i monitoring (X/7)**
   - Ocena jakości KPI
   - Praktyczność systemu monitoringu

### KLUCZOWE ZALECENIA
1. **Najważniejsze mocne strony**:
   - [lista 3-5 najlepszych elementów]

2. **Krytyczne obszary do poprawy**:
   - [lista 3-5 najważniejszych braków]

3. **Konkretne sugestie ulepszeń**:
   - [szczegółowe rekomendacje poprawek]

### DODATKOWE UWAGI
- Czy raport spełnia standardy profesjonalnego dokumentu strategicznego?
- Czy język i ton są odpowiednie dla odbiorcy biznesowego?
- Czy formatowanie i struktura markdown są poprawne?

### REKOMENDACJE POPRAWEK RAPORTU
*(Wypełnij tylko jeśli WYNIK = AKCEPTUJĘ, ale są obszary do optymalizacji)*

#### CO MOŻNA JESZCZE ULEPSZYĆ W RAPORCIE:

**1. Wzmocnienie mocnych stron:**
- [wskaż które fragmenty są szczególnie udane i mogłyby być rozszerzone]

**2. Dodatkowe szczegóły:**
- [które sekcje mogłyby być bardziej rozbudowane]
- [jakie dodatkowe informacje wzbogaciłyby raport]

**3. Usprawnienia stylistyczne:**
- [sugestie dotyczące czytelności i prezentacji]
- [propozycje lepszego formatowania]

**4. Dodatkowe wartości:**
- [jakie elementy mogłyby zwiększyć praktyczną wartość raportu]
- [dodatkowe przykłady lub case studies]

---
"""

[consensus]
consensus_prompt = """You are a strategic consultant tasked with creating a comprehensive AI transformation report. Generate ONLY the report content without any conversational responses, introductions, or meta-commentary.

TASK: Build a detailed strategic report (at least 7000 words) that:
1. Synthesizes the best insights from all analyses
2. Contains practical, actionable recommendations
3. Has the character of a professional strategic document

IMPORTANT: Generate a complete, comprehensive report with all sections. Target at least 7000 words to ensure exhaustive coverage of all strategic aspects with deep analysis and detailed implementation guidance.

## INPUT DATA

### GAP ANALYSIS (COMMON SOURCE OF TRUTH):
{gaps_data}

### INDEPENDENT AI ANALYSES (FOR SYNTHESIS):
{branch_data}

## SYNTHESIS METHODOLOGY AND QUALITY REQUIREMENTS

### 1. COMPARATIVE SOURCE ANALYSIS
- **Identify the strongest elements of each analysis**: Which report has the best structure? Most detailed budgets? Most realistic timelines?
- **Find common threads and confirmations**: Elements repeated across all analyses have high credibility
- **Identify unique valuable insights**: Each model can bring unique perspectives that will enrich the final report
- **Assess recommendation quality**: Prioritize concrete, actionable actions over general concepts

### 2. REPORT CONSTRUCTION REQUIREMENTS

**STRUCTURE:**
1. **Executive Summary** - Key findings and transformation priorities (500-700 words)
2. **Current State Assessment** - Detailed analysis of organizational maturity (800-1000 words)
3. **Priority Areas Analysis** - Focus on areas from gaps data only (2000-2500 words)
4. **Implementation Plan** - Comprehensive 3-phase roadmap with timelines and budgets (2000-2500 words)
5. **Success Metrics** - KPIs, monitoring approach, and measurement frameworks (600-800 words)
6. **Business Benefits** - ROI estimates, competitive advantages, and strategic value (600-800 words)
7. **Risk Management** - Comprehensive mitigation strategies and contingency plans (500-700 words)
8. **Change Management** - Organizational transformation approach and stakeholder engagement (400-600 words)
9. **Conclusion** - Summary and next steps (300-400 words)

### 3. STYLISTIC GUIDELINES

**LANGUAGE AND TONE:**
- Professional but accessible business language
- Narrative style with logical flow of arguments
- Concrete examples and case studies where possible
- Balance between vision and practicality
- Detailed explanations with supporting rationale
- Executive-level strategic perspective with operational depth

**VISUAL ELEMENTS (in markdown):**
- Comprehensive comparison tables for key metrics
- Detailed checklists for practical actions
- Highlights and callouts for key insights
- Logical hierarchy of headings and subsections
- Timeline charts and implementation roadmaps
- Budget breakdowns and cost-benefit analyses

**CONCRETENESS AND ACTIONABILITY:**
- Provide specific names of technologies, vendors, tools with detailed descriptions
- Set realistic budgets with detailed ranges and justifications
- Set measurable goals and deadlines with milestone tracking
- Indicate people/roles responsible for specific areas with skill requirements
- Include step-by-step implementation instructions
- Provide templates and frameworks for execution

## FINAL TASK

Create a **COMPREHENSIVE AI TRANSFORMATION REPORT** that:
- Constitutes a synthesis of the best elements from all three analyses
- Is significantly more detailed and narrative than previous reports
- Contains practical, actionable recommendations with concrete details
- Serves as a complete strategic guide for the organization
- Has the structure of a professional consulting document
- Provides exhaustive coverage of all transformation aspects
- Includes detailed implementation guidance and best practices

The report should be detailed and practical enough that the organization can use it as the main document guiding the entire AI transformation, serving as both strategic roadmap and operational handbook.

CRITICAL REQUIREMENTS:
- Report must be written in POLISH language
- Generate a comprehensive report targeting at least 7000 words
- Start IMMEDIATELY with the report title - no conversational text, acknowledgments, or preambles
- Do NOT include phrases like "Jasne, oto raport" or similar conversational responses
- Begin directly with the report header (e.g., "# Strategiczny Raport Transformacji AI")
- Complete all sections with detailed, substantive content and deep analysis
- Focus on exhaustive analysis of the priority areas in gaps data
- Provide actionable recommendations with realistic timelines and detailed budgets
- Ensure each section meets the suggested word count for comprehensive coverage
- Include extensive examples, case studies, and implementation templates
- Provide detailed explanations and justifications for all recommendations

OUTPUT FORMAT: Start immediately with the report title and content. No meta-text."""