# Configuration for areas to analyze for gaps in OLIMP questionnaire
# These sections will be analyzed to identify improvement opportunities

[gap_analysis]
target_sections = [
    "TECHNOLOGIA I INFRASTRUKTURA",
    "DANE", 
    "LUDZIE I KOMPETENCJE", 
    "ORGANIZACJA I PROCESY",
    "STRATEGIA I ZARZĄDZANIE",
    "BUDŻET",
    "PRODUKTY I USŁUGI",
    "ETYKA I REGULACJE"
]